-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghoPMNIS8XMgaMoq2
Zmz0vwhGWfjJ8snMsWqZA2B9nzmgCgYIKoZIzj0DAQehRANCAAROPx2A3RB06RdY
eRdDsjnE2NovVwYaLu2UwfnXKm6VFvZkuNh9nXfEF9DReKLg5Z7regqbRSMBZnt7
F2KXwt0W
-----END PRIVATE KEY-----